spring:
  datasource:
    url: jdbc:h2:mem:stw2025
    driverClassName: org.h2.Driver
    username: stw2025
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8080
